server:
  port: 8082

spring:
  #  config:
  #    activate:
  #      on-profile: local
  redis:
    host: localhost
    #    redis 고유 port
    port: 6379

  #RabbitMQ 환경설정
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  #    virtual-host: /

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/myorder
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

logging:
  level:
    root: info

jwt:
  expiration: 30
  secretKey: my_token_secret
  expirationRt: 60
  secretKeyRt: hackerton_secret

#aws s3 설정
cloud:
  aws:
    credentials:
      access-key: TEST # 엑세스 키
      secret-key: TEST # 비밀 키
    region:
      static: ap-northeast-2
    s3:
      bucket: moori-file
