name: deploy to ec2 with docker
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
    
      - name: build image
        working-directory: .
        run: docker build -t moori98/ordersystem:latest .

      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_EMAIL}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: push to dockerhub
        run: docker push moori98/ordersystem:latest
      
      - name: ec2 ssh login and docker compose update
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-36-109-253.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{secrets.EC2_PEMKEY}}
          script: |
            if ! type docker > /dev/null ; then
              sudo snap install docker || echo "docker install failed"
            fi
            sudo docker login --username ${{secrets.DOCKER_EMAIL}} --password ${{secrets.DOCKER_PASSWORD}}

            sudo docker-compose pull && sudo docker-compose up -d


# ec2 instance에 docker-compose 파일을 전송하기 위한 명령어
# => pemkey 가 있는 위치로 가서 해준다(나는 Download 위치)
# scp -i "my-keypair.pem" C:\Users\anflw\Desktop\BeyondCamp\ordersystem\docker-compose.yml ubuntu@ec2-3-36-109-253.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/